version: '3.7'
services:
  yafr:
    image: rozbujnik/simple-crawler
    container_name: simple-crawler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      ALLOWED_IP: "192.168.0.1"
      YAFR_HOST: "0.0.0.0"
      YAFR_PORT: 4000
